### ISSUE TITLE
Incomplete SECH-Tags-List

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#27]
Easy to reproduce:
1) Start brwoser
2) Click on "Home"
3) Click on "Bildung"
4) Wait a moment
5) Open SeCH-List-Menu

Result: Screen Shot
![bildschirmfoto 2016-01-15 um 17 30 19](https://cloud.githubusercontent.com/assets/14542721/12358479/b5ddfb0c-bbad-11e5-881c-d3d2715796bc.png)

Clicking on one of these empty entries leads to a crash

**Comment by bmairhoermann** [comment]
This bug is caused by special-charachters in the Attribute "topic".
I am on it fixing the Regex.

**Comment by bmairhoermann** [comment]
Done

**Comment by pstoehr** [comment]
Reopened as "Klar der Große" is still missing ...
![bildschirmfoto 2016-01-16 um 17 02 49](https://cloud.githubusercontent.com/assets/14542721/12373239/2a889456-bc73-11e5-8dd4-bfc7e5ee8ecb.png)

**Comment by bmairhoermann** [comment]
Forgot the ß.

_why are there so many special letters in german_
